### ISSUE TITLE
Missing Directories

### ISSUE THREAD

**Issue by MarcelTO** [StukiOrg/RollnApi#6]
Where are the ~/bin and ~/documentation directories referred to on [http://rollnapi-tomanderson.rhcloud.com](http://rollnapi-tomanderson.rhcloud.com "rollnapi").  I don't have the words to express the awesomeness of this project.  I'd really like to be able to follow the tutorial and it looks like I'm not the only one [http://stackoverflow.com/questions/27009813/configuring-rolln-api](http://stackoverflow.com/questions/27009813/configuring-rolln-api).

**Comment by TomHAnderson** [comment]
Alas Roll'n API isn't up with all the latest and greatest because it's used as a demo app.  It will be updated when Doctrine is supported across the board for the API.  See https://github.com/TomHAnderson/apigility-doctrine-skeleton for the latest work.
