### ISSUE TITLE
zfcampus/zf-doctrine-querybuilder-filter Abandoned

### ISSUE THREAD

**Issue by MarcelTO** [StukiOrg/RollnApi#7]
I had to change the require entry to "zfcampus/zf-doctrine-querybuilder": "1.0.*@dev" and remove the repository from the composer.json file to get composer to do the install and get the example api running.  Still not sure how to do a (re)build though (no ~/bin) though.

**Comment by TomHAnderson** [comment]
You found the correct zf-doctrine-querybuilder as -filter was renamed.  

Roll'n API will be updated when my current work is complete: https://github.com/TomHAnderson/apigility-doctrine-skeleton  This project is a Doctrine OAuth2 server and very much in the development stage.
