### ISSUE TITLE
Installation via composer requires credentials (bacause of https://github.com/TomHAnderson/zf-doctrine-querybuilder-filter).

### ISSUE THREAD

**Issue by automatix** [StukiOrg/RollnApi#9]
@TomHAnderson 

The StukiOrg/RollnApi installation process requires your GitHub account credentials. The repo behind the credentials is https://github.com/TomHAnderson/zf-doctrine-querybuilder-filter.

    $ composer install
    Loading composer repositories with package information
    Your GitHub credentials are required to fetch private repository metadata (https://github.com/TomHAnderson/zf-doctrine-querybuilder-filter)
    The credentials will be swapped for an OAuth token stored in /root/.composer/auth.json, your password will not be stored
    To revoke access to this token you can visit https://github.com/settings/applications
    Username: 
    Password: 
    Invalid credentials.

**Comment by adamlundrigan** [comment]
That's a strange error given that the repository is public (maybe it wasn't 4 days ago?).  Alternatively, there's a fork of that repository on the `zfcampus` organization that you should be able to use:  https://github.com/zfcampus/zf-doctrine-querybuilder

**Comment by automatix** [comment]
Yes, the error occured some days ago, maybe 4 days ago, a don't
    remember. I also tried to use zf-doctrine-querybuilder instead, but
    it didn't work correctly as well. Here I described my approach:
    https://github.com/StukiOrg/RollnApi/pull/8#issue-56028056 (oh, I
    see now, the PR was created 4 days ago...). (I closed my PR, since
    at the end I was not sure, what caused the error and whether my
    changes were correct.) I have just tried it again:
    
    $ git clone
      https://github.com/StukiOrg/RollnApi.git .
      Cloning into '.'...
      remote: Counting objects: 1566, done.
      
      
      Resolving deltas: 100% (543/543), done.
      
      $ php -r "readfile('https://getcomposer.org/installer');" | php
      #!/usr/bin/env php
      All settings correct for using Composer
      Downloading...
      
      Composer successfully installed to:
      /var/www/sandbox/RollnApi-test/composer.phar
      Use it: php composer.phar
      myuser@myvm:/var/www/sandbox/RollnApi-test# ./composer.phar
      install
      Loading composer repositories with package information
      Your GitHub credentials are required to fetch private repository
      metadata
      (https://github.com/TomHAnderson/zf-doctrine-querybuilder-filter)
      The credentials will be swapped for an OAuth token stored in
      /root/.composer/auth.json, your password will not be stored
      To revoke access to this token you can visit
      https://github.com/settings/applications
      Username: 
      Password: 
      Invalid credentials.
    
    The other "RollnApi" repo TomHAnderson/RollnApi
    (https://github.com/TomHAnderson/RollnApi) can be "installed" with
    composer.
    
    
    
    Am 03.02.2015 um 15:08 schrieb Adam Lundrigan:
    
      That's a strange error given that the repository is public
        (maybe it wasn't 4 days ago?). Alternatively, there's a fork of
        that repository on the zfcampus organization that
        you should be able to use: https://github.com/zfcampus/zf-doctrine-querybuilder
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by TomHAnderson** [comment]
This version of Roll'n API is old and I'm going to remove it.  See https://github.com/TomHAnderson/RollnApi for it's successor.
